# Chapter 2. Numpy - 선형 대수학

In [1]:
import numpy as np

# 1. 복습

## Vector : 벡터

In [2]:
v1 = np.array([1, 5, -4])
print(v1)

[ 1  5 -4]


## Matrix : 행렬
* 2차원 배열

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


## Tensor
* 3차원 이상의 배열
* 한국 용어는 없음

## 내적
* |a||b| cos θ = a · b
* cos θ = a · b / |a||b|
* 데이터 분석에서 외적은 사용하지 않아서 Pass

In [4]:
v1 = np.array([5,0])
v2 = np.array([-4,0])
np.dot(v1, v2)

-20

In [5]:
v1 = np.array([5,0])
v2 = np.array([-2,4])
np.dot(v1, v2)

-10

In [6]:
v1 = np.array([5,1])
v2 = np.array([-2,4])
np.dot(v1, v2)

-6

# 2. 행렬 내적
* A(m x n) · B(n x r) = C(m x r)

In [7]:
arr1 = np.array([[1,2],[3,4],[5,6]]) # 3행 2열
arr2 = np.array([[6,23],[-1,7],[8,9]]) # 3행 2열
np.dot(arr1, arr2.T) # (3 x 2) · (2 x 3) = (3 x 3)

array([[ 52,  13,  26],
       [110,  25,  60],
       [168,  37,  94]])

In [8]:
np.dot(arr1.T, arr2) # (2 x 3) · (3 x 2) = (2 x 2)

array([[ 43,  89],
       [ 56, 128]])

# 3. Iris 데이터로 Numpy 응용

In [9]:
from sklearn.datasets import load_iris

In [10]:
data = load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## 데이터 확인

In [11]:
data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 데이터 정리

In [13]:
X = data['data']
Y = data['target']
print(X.shape, Y.shape)

(150, 4) (150,)


In [14]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 통계값 구하기

### Ex)
Setosa(Y = 0)의 평균과 표준편차를 구하세요.

In [15]:
print('평균\n', X[Y == 0].mean(axis = 0))
print('\n표준편차\n', X[Y == 0].std(axis = 0))

평균
 [5.006 3.428 1.462 0.246]

표준편차
 [0.34894699 0.37525458 0.17191859 0.10432641]


### Ex)
target별 통계값을 구하세요.

In [16]:
for i in range(3) :
    print(data.target_names[i])
    print('평균',X[Y == i].mean(axis = 0))
    print('표준편차',X[Y == i].std(axis = 0))
    print('')

setosa
평균 [5.006 3.428 1.462 0.246]
표준편차 [0.34894699 0.37525458 0.17191859 0.10432641]

versicolor
평균 [5.936 2.77  4.26  1.326]
표준편차 [0.51098337 0.31064449 0.46518813 0.19576517]

virginica
평균 [6.588 2.974 5.552 2.026]
표준편차 [0.62948868 0.31925538 0.54634787 0.27188968]



# 4. Cos 유사도(코사인 유사도)

In [17]:
print('Setosa(Y = 0)인 첫번째 값')
print(X[Y == 0][0])
print('\nSetosa(Y = 0)인 전체 값의 평균')
print(X[Y == 0].mean(axis = 0))

Setosa(Y = 0)인 첫번째 값
[5.1 3.5 1.4 0.2]

Setosa(Y = 0)인 전체 값의 평균
[5.006 3.428 1.462 0.246]


## 벡터 정규화

In [18]:
np.linalg.norm(X[Y == 0][0])

6.345076831686122

## 코사인 유사도 함수

In [19]:
def cos_sim(a, b) :
    return np.dot(a, b.T) / (np.linalg.norm(a) * np.linalg.norm(b))

In [20]:
cos_sim(X[Y == 0][0], X[Y == 0].mean(axis = 0))

0.9998724340174694

In [21]:
np.dot(X, X[Y == 0].mean(axis = 0)).shape

(150,)

In [22]:
sample = X[Y == 2][0:1]
setosa = X[Y == 0].mean(axis = 0)
cos_sim(sample, setosa)

array([0.86806512])

## 실습
Iris 데이터와 코사인 유사도를 활용하여 분류 모델을 생성하세요.

In [23]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [24]:
setosa = X[Y == 0].mean(axis = 0)
versicolor = X[Y == 1].mean(axis = 0)
virginica = X[Y == 2].mean(axis = 0)

In [25]:
setosa_cos_sim = cos_sim(X, setosa)
versicolor_cos_sim = cos_sim(X, versicolor)
virginica_cos_sim = cos_sim(X, virginica)

print(setosa_cos_sim.shape)
print(versicolor_cos_sim.shape)
print(virginica_cos_sim.shape)

(150,)
(150,)
(150,)


In [26]:
total_cos_sim = np.stack([setosa_cos_sim, versicolor_cos_sim, virginica_cos_sim])
total_cos_sim.shape

(3, 150)

In [27]:
np.argmax(total_cos_sim, axis = 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [28]:
pred = np.argmax(total_cos_sim, axis = 0)
round(np.sum(pred == Y) / len(Y), 4)

0.9733

# 5. Inplace
* 일반 연산은 copy()
* Inplace 연산은 view()

In [29]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1[1:3]
arr2

array([2, 3])

In [30]:
# 일반 연산
arr2 = arr2 * 10
# Inplace 연산
arr2 *= 10