# Chapter 2. Numpy - 배열 조작과 인덱싱

# 1. Numpy 개요
* Numpy는 대용량 배열과 행렬 연산에 대한 고속 연산을 지원하는 라이브러리
* 딥러닝에 입력으로 들어가는 이미지는 4차원 데이터(Batch-size, 높이, 너비, 채널 수)
* Numpy는 벡터화 계산으로 속도가 매우 빠르고, 시간을 많이 단축할 수 있어 대용량 데이터 처리에 유용하다.

In [1]:
import numpy as np

## 예시

In [2]:
import time

### 반복문 연산 예시

In [3]:
start_time = time.time()

num = range(1,1000000)
s = []

for i in num :
    s.append(i**2)
    
end_time = time.time()

print(end_time - start_time)

0.2573378086090088


### Numpy 연산 예시

In [4]:
start_time = time.time()

num = np.arange(1,1000000)
s = np.square(num)

end_time = time.time()

print(end_time - start_time)

0.00897669792175293


* 반복문 연산과 Numpy 연산의 속도에는 아주 큰 차이가 있는 것을 확인할 수 있다.

# 2. Dimension (차원)

## 1차원 배열

In [5]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
print('배열 형태 :',arr1.shape)
print('배열 차원 :',arr1.ndim)
print('배열 내부 원소의 자료형 :',arr1.dtype)
print('배열 내부 원소의 크기 :',arr1.itemsize)
print('배열 내부 원소의 개수 :',arr1.size)

배열 형태 : (5,)
배열 차원 : 1
배열 내부 원소의 자료형 : int32
배열 내부 원소의 크기 : 4
배열 내부 원소의 개수 : 5


## 2차원 배열 
* np.array( [ [ ] ] ) : [ ] 괄호(대괄호)의 개수를 보고 차원을 알 수 있다.

In [7]:
arr2 = np.array([[1],[2],[3],[4],[5]])
arr2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
print('배열 형태 :',arr2.shape)
print('배열 차원 :',arr2.ndim)
print('배열 내부 원소의 자료형 :',arr2.dtype)
print('배열 내부 원소의 크기 :',arr2.itemsize)
print('배열 내부 원소의 개수 :',arr2.size)

배열 형태 : (5, 1)
배열 차원 : 2
배열 내부 원소의 자료형 : int32
배열 내부 원소의 크기 : 4
배열 내부 원소의 개수 : 5


### 예제
( 3, 3 ) 형태의 배열을 만들고 형태, 차원수, 내부 원소의 자료형, 원소의 크기, 내부 원소의 개수를 출력하는 코드를 작성하세요.

In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print('배열 형태 :',arr.shape)
print('배열 차원 :',arr.ndim)
print('배열 내부 원소의 자료형 :',arr.dtype)
print('배열 내부 원소의 크기 :',arr.itemsize)
print('배열 내부 원소의 개수 :',arr.size)

배열 형태 : (3, 3)
배열 차원 : 2
배열 내부 원소의 자료형 : int32
배열 내부 원소의 크기 : 4
배열 내부 원소의 개수 : 9


## 3차원 배열

In [10]:
arr3 = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
arr3.shape

(2, 2, 2)

In [11]:
arr3 = np.array([[[1,2],[4,3],[7,4]],
                 [[2,3],[9,0],[7,5]],
                 [[1,2],[3,4],[0,2]],
                 [[9,0],[6,7],[9,8]]])

print('배열 :\n', arr3)
print('\n배열 형태 :',arr3.shape)
print('배열 차원 :',arr3.ndim)
print('배열 내부 원소의 자료형 :',arr3.dtype)
print('배열 내부 원소의 크기 :',arr3.itemsize)
print('배열 내부 원소의 개수 :',arr3.size)

배열 :
 [[[1 2]
  [4 3]
  [7 4]]

 [[2 3]
  [9 0]
  [7 5]]

 [[1 2]
  [3 4]
  [0 2]]

 [[9 0]
  [6 7]
  [9 8]]]

배열 형태 : (4, 3, 2)
배열 차원 : 3
배열 내부 원소의 자료형 : int32
배열 내부 원소의 크기 : 4
배열 내부 원소의 개수 : 24


# 3. Function 1 (함수)

## np.zero
* 배열 전체를 0으로 채우기

In [12]:
arr_zero = np.zeros((4,3,2), dtype = int)
arr_zero

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

* 1차원 내부 값 개수 : 2
* 2차원 내부 값 개수 : 3
* 3차원 내부 값 개수 : 4

## np.ones
* 배열 전체를 1으로 채우기

In [13]:
arr_ones = np.ones((2,2,3), dtype = str)
arr_ones

array([[['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1']]], dtype='<U1')

* 1차원 내부 값 개수 : 3
* 2차원 내부 값 개수 : 2
* 3차원 내부 값 개수 : 2

## np.full
* 배열 전체를 특정 값으로 채우기

In [14]:
# 배열 전체를 1으로 채우기
arr_full = np.full((2,3,3),1)
arr_full

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

* 1차원 내부 값 개수 : 3
* 2차원 내부 값 개수 : 3
* 3차원 내부 값 개수 : 2

## np.arange
* 지정된 범위 내에서 지정된 간격으로 일정한 값의 배열을 생성
* arange는 반드시 1차원 배열

In [15]:
# 예시 1
arr_arange1 = np.arange(10)
arr_arange1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# 예시 2
arr_arange2 = np.arange(1,10,2)
arr_arange2

array([1, 3, 5, 7, 9])

## np.reshape
* 배열의 형태를 변경
* 각 차원의 수를 곱한 값은 항상 일정해야 함

In [17]:
# 1차원 배열을 2차원 배열로 변경
arr = np.array([0,1,2,3,4,5,6,7,8,9])

arr_reshape = arr_arange1.reshape(2,5)
arr_reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## np.linspace
* 지정된 범위에서 지정된 개수만큼 동일한 간격으로 일정한 값의 배열을 생성

In [18]:
# 예시 1
arr_linspace1 = np.linspace(0, 1, 5)
arr_linspace1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# 예시 2
arr_linspace2 = np.linspace(0, 2*np.pi, 10)
arr_linspace2

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

# 4. Calculate (연산)

## 1차원 배열

In [20]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

### v1 + v2

In [21]:
v1 + v2

array([5, 7, 9])

### v1 + 상수

In [22]:
v1 + 10

array([11, 12, 13])

### v1 * v2

In [23]:
v1 * v2

array([ 4, 10, 18])

### v1 ** v2

In [24]:
v1 ** v2

array([  1,  32, 729])

## 2차원 배열

In [25]:
v1 = np.array([[1,2],[3,4]])
v2 = np.array([[5,6],[7,8]])

### v1 + v2

In [26]:
v1 + v2

array([[ 6,  8],
       [10, 12]])

### v1 + np.array

In [27]:
v1 + np.array([[10],[100]])

array([[ 11,  12],
       [103, 104]])

### Boolean

In [28]:
v1 > 1

array([[False,  True],
       [ True,  True]])

In [29]:
v1 > v2

array([[False, False],
       [False, False]])

In [30]:
v1 != 3

array([[ True,  True],
       [False,  True]])

In [31]:
v1 % 2

array([[1, 0],
       [1, 0]], dtype=int32)

In [32]:
v1 % 2 == 0

array([[False,  True],
       [False,  True]])

# 5. Slicing (슬라이싱)

In [33]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [34]:
v1[1:]

array([2, 3, 4, 5])

In [35]:
v1[:-1]

array([1, 2, 3, 4])

In [36]:
v1[0]

1

In [37]:
v1[1]

2

In [38]:
v2 = np.array([[1,2],[3,4]])
v2

array([[1, 2],
       [3, 4]])

In [39]:
v2[1]

array([3, 4])

In [40]:
v2[0][1]

2

In [41]:
v2[0,1]

2

In [42]:
v2[:] = [0,1]
v2

array([[0, 1],
       [0, 1]])

In [43]:
v2[:] = [[100],[200]]
v2

array([[100, 100],
       [200, 200]])

## 예제
* 1차원 내부 값 개수 : 5개
* 2차원 내부 값 개수 : 4개
* 3차원 내부 값 개수 : 3개
* 4차원 내부 값 개수 : 2개

In [44]:
zero = np.zeros((2,3,4,5))
zero

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

### 1번
4차원 첫 번째, 3차원 세 번째, 2차원 세 번째의 1차원 배열 전체를 1로 변경

In [45]:
zero = np.zeros((2,3,4,5))
zero[0,2,2] = 1
zero

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

### 2번
4차원 첫 번째의 인덱스 1번 전체를 1로 변경

In [46]:
zero = np.zeros((2,3,4,5))
zero[0,:,:,1] = 1
zero

array([[[[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

### 3번
4차원 첫 번째, 3차원 두 번째 이후의 모든 배열 전체를 1로 변경

In [47]:
zero = np.zeros((2,3,4,5))
zero[0,1:,:,:] = 1
zero

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

# 6. 실습 문제

## 1번
Numpy 배열을 생성하고, 아래의 문제를 해결하세요.

### 1).
3, 3 크기의 2차원 배열을 생성하고, 모든 요소를 0으로 초기화하세요.

In [48]:
arr = np.zeros((3,3), dtype = int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### 2).
5개의 랜덤 정수로 이루어진 1차원 Numpy 배열을 생성하세요.  
이 때, 각 요소의 값은 0이상 9이하의 정수 중에서 무작위로 선택되어야 합니다.

In [49]:
arr = np.random.randint(low = 2, high = 9, size = 5)
arr

array([6, 7, 7, 2, 8])

### 3).
2, 3, 4 크기의 3차원 Numpy 배열을 생성하고, 모든 요소의 값을 1로 설정하세요.

In [50]:
arr = np.ones((2,3,4), dtype = int)
arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

## 2번
Numpy 배열을 생성하고, 아래의 문제를 해결하세요.

In [51]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### 1).
크기 확인

In [52]:
arr.shape

(2, 3)

### 2).
요소 개수 확인

In [53]:
arr.size

6

### 3).
데이터 타입 확인

In [54]:
arr.dtype

dtype('int32')

## 3번
다음과 같이 두 개의 Numpy 배열이 있다고 가정하고, 아래의 문제를 해결하세요.

In [55]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

### 1).
두 배열을 더하기

In [56]:
arr1 + arr2

array([5, 7, 9])

### 2).
두 배열을 빼기

In [57]:
arr1 - arr2

array([-3, -3, -3])

### 3).
두 배열을 곱하기

In [58]:
arr1 * arr2

array([ 4, 10, 18])

### 4).
두 배열을 나누기

In [59]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

### 5).
첫 번째 배열을 제곱하기

In [60]:
arr1 ** 2

array([1, 4, 9])

### 6).
두 배열 각각의 평균 구하기

In [61]:
(arr1 + arr2) / 2

array([2.5, 3.5, 4.5])

## 4번
모든 요소가 0인 5, 5 크기의 Numpy 배열을 만든 후, 모든 요소의 값을 5로 변경하세요.

In [62]:
arr = np.zeros((5,5))
arr += 5
arr

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

## 5번
Numpy 배열 arr = np.array( [ 1, 2, 3, 4, 5, 6 ] )이 있습니다.  
Boolean Indexing을 활용하여 [ 1, 3, 5 ]를 출력하세요.

In [63]:
arr = np.array([1,2,3,4,5,6])
arr[arr % 2 != 0]

array([1, 3, 5])

## 6번
Numpy 배열 arr = np.array( [ 1, 2, 3, 4, 5, 6 ] )이 있습니다.  
Fancy Indexing을 활용하여 [ 1, 3, 5 ]를 출력하세요.

In [64]:
arr = np.array([1,2,3,4,5,6])
arr[[0,2,4]]

array([1, 3, 5])